remote_theme: pages-themes/leap-day@v0.2.0
plugins: - jekyll-remote-theme
title: "Paul Haynes ePortfolio"
description: "Showcasing my journey from instructional design and systems training to cybersecurity."
